version: '3.8'

services:
  web:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.dev
  redis:
    image: redis:alpine
  celery:
    build: ./api
    command: celery -A api worker -l info
    volumes:
      - ./api/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
  celery-beat:
    build: ./api
    command: celery -A api beat -l info
    volumes:
      - ./api/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis

volumes:
  postgres_data:
