# Generated by Django 3.2.4 on 2021-08-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_source', models.CharField(choices=[('youtube', 'Youtube'), ('tiktok', 'Tiktok'), ('insta_reel', 'Instagram Reels')], default='youtube', max_length=16)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField(db_index=True)),
                ('thumbnails', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'api_video',
            },
        ),
    ]
